#spring
spring:
  datasource:
    url: jdbc:mysql://mysql57.rdsmc5gff9sm7gq.rds.bj.baidubce.com/pet_community?serverTimezone=GMT%2B8&characterEncoding=utf8
    username: root
    password: petc123456
  thymeleaf:
    prefix: classpath:/templates/pages/
    suffix: .html
    cache: false
  aop:
    proxy-target-class: false
  profiles:
    active: dev     #指定当前使用的是生产环境配置

#server
server:
  port: 80
  servlet:
    context-path: /
  tomcat:
    max-threads: 1000
    uri-encoding: utf-8

#mybatis
mybatis:
  configuration:
    default-statement-timeout: 30
    map-underscore-to-camel-case: true
  mapper-locations:
  - classpath:/mapper/*/*.xml

#lOG
logging:
  level:
    com.tedu: DEBUG

#async-thread-pool
async-thread-pool:
  corePoolSize: 20
  maxPoolSize: 1000
  keepAliveSeconds: 30
  queueCapacity: 1000

---
spring:
  profiles: dev

#github oauth设置github登录的相关参数
github:
  client:
    id: 118fa472013f6a21d78d
    secret: 6d44ce3c905259dc1e2c040c7c8bb913fc265109
  redirect:
    uri: http://localhost/callback

---
spring:
  profiles: prod

#github oauth设置github登录的相关参数
github:
  client:
    id: 118fa472013f6a21d78d
    secret: 6d44ce3c905259dc1e2c040c7c8bb913fc265109
  redirect:
    uri: http://111.229.41.3/callback